### ISSUE TITLE
Table or view `t_ent_order` does not exist

### ISSUE THREAD

**Issue by v8v6** [trydofor/professional-wings#263]
Hello,Thank you for taking a look at this issue for me！

version：5.4.1
springboot：2.6.3

```
application.yml

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
    
    
    
sharding.yaml

dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds3:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root

rules:
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: ds0
  - !SHARDING
    tables:
      # 订单表基础表
      t_ent_order:
        # 真实表
        actualDataNodes: ds0.t_ent_order_$->{0..2}
        # 分库策略
        databaseStrategy:
          complex:
            shardingColumns: id,ent_id
            shardingAlgorithmName: hash-slot-algorithm
      # 订单详情表
      t_ent_order_detail:
        actualDataNodes: ds0.t_ent_order_detail_$->{0..2}
        # 分库策略
        databaseStrategy:
          complex:
            shardingColumns:  id,ent_id
            shardingAlgorithmName: hash-slot-algorithm
      # 订单条目表
      t_ent_order_item:
        actualDataNodes: ds0.t_ent_order_item_$->{0..7}

        # 分表策略
        tableStrategy:
          complex:
            shardingColumns: id,ent_id
            shardingAlgorithmName: hash-slot-table-algorithm
    # 绑定表
    bindingTables:
      - t_ent_order,t_ent_order_detail

    # 分片算法
    shardingAlgorithms:
      hash-slot-algorithm:
        type: CLASS_BASED
        props:
          strategy: complex
          algorithmClassName: cn.javayong.shardingjdbc5.spring.common.sharding.HashSlotAlgorithm
      hash-slot-table-algorithm:
        type: CLASS_BASED
        props:
          strategy: complex
          algorithmClassName: cn.javayong.shardingjdbc5.spring.common.sharding.HashSlotAlgorithm
          # 非默认值，直接对分片数取余
          directIndex: true

  # 广播
  - !BROADCAST
    tables:
      - t_address

props:
  # 日志显示 SQL
  sql-show: true
    

```
